/**
 * @file packages/database/models/Job.js
 * @description Sequelize model for the `jobs` table.
 *
 * Design notes:
 *  - UUID v4 primary keys are generated by the application layer (not MySQL)
 *    for compatibility with multi-region insert patterns.
 *  - ENUM values are kept in sync with the MySQL DDL; Sequelize validates at
 *    the ORM layer before the query hits the wire.
 *  - Composite indexes mirror the DDL's critical dispatch/scan indexes so
 *    that Sequelize's `sync({ alter: true })` keeps them in place.
 *  - `payload` and `tags` are stored as JSON; Sequelize handles serialization.
 */

import { DataTypes, Model } from 'sequelize';
import { v4 as uuidv4 }     from 'uuid';

// ---------------------------------------------------------------------------
// Enumerations (single source of truth â€” import these in service code)
// ---------------------------------------------------------------------------

/** Mirrors the `status` ENUM in the DDL exactly. */
export const JobStatus = Object.freeze({
  PENDING:   'PENDING',
  SCHEDULED: 'SCHEDULED',
  QUEUED:    'QUEUED',
  RUNNING:   'RUNNING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED:    'FAILED',
  CANCELLED: 'CANCELLED',
  DEAD:      'DEAD',
});

/**
 * Retry back-off strategy applied when a job transitions to FAILED
 * and retry_count < max_retries.
 */
export const RetryStrategy = Object.freeze({
  EXPONENTIAL: 'EXPONENTIAL', // delay = base * 2^attempt  (default)
  LINEAR:      'LINEAR',      // delay = base * attempt
  FIXED:       'FIXED',       // delay = base (constant)
});

// ---------------------------------------------------------------------------
// Model definition
// ---------------------------------------------------------------------------

/**
 * @class Job
 * @extends {Model}
 */
export class Job extends Model {
  /**
   * Factory initialiser. Call once during bootstrap (see index.js).
   * @param {import('sequelize').Sequelize} sequelize - Configured Sequelize instance.
   */
  static initialize(sequelize) {
    Job.init(
      {
        // â”€â”€ Primary Key â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        id: {
          type:         DataTypes.UUID,
          primaryKey:   true,
          defaultValue: uuidv4,
          allowNull:    false,
          comment:      'UUIDv4 â€” generated in application layer.',
        },

        // â”€â”€ Foreign Keys â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        queue_id: {
          type:      DataTypes.UUID,
          allowNull: false,
          comment:   'FK â†’ queues.id. Determines dispatch channel.',
        },

        worker_id: {
          type:      DataTypes.UUID,
          allowNull: true,
          defaultValue: null,
          comment:   'FK â†’ workers.id. Set atomically during claim transaction.',
        },

        parent_job_id: {
          type:      DataTypes.UUID,
          allowNull: true,
          defaultValue: null,
          comment:   'Self-referential FK for fan-out / chained job trees.',
        },

        created_by: {
          type:      DataTypes.UUID,
          allowNull: true,
          defaultValue: null,
          comment:   'FK â†’ users.id. NULL for system-generated cron jobs.',
        },

        // â”€â”€ Core Fields â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        name: {
          type:      DataTypes.STRING(200),
          allowNull: false,
          comment:   'Human-readable job name for observability.',
        },

        payload: {
          type:         DataTypes.JSON,
          allowNull:    false,
          defaultValue: {},
          comment:      'Opaque JSON input forwarded to the executor.',
        },

        status: {
          type:         DataTypes.ENUM(...Object.values(JobStatus)),
          allowNull:    false,
          defaultValue: JobStatus.PENDING,
          comment:      'Job lifecycle state. Transitions enforced by Scheduler.',
        },

        // â”€â”€ Scheduling & Prioritization â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        priority: {
          type:         DataTypes.TINYINT.UNSIGNED,
          allowNull:    false,
          defaultValue: 5,
          comment:      '1 (lowest) â€“ 10 (critical). Used in dispatch ORDER BY.',
          validate: {
            min: 1,
            max: 10,
          },
        },

        cron_expression: {
          type:         DataTypes.STRING(100),
          allowNull:    true,
          defaultValue: null,
          comment:      'Standard cron string. NULL for one-shot jobs.',
        },

        scheduled_at: {
          type:      DataTypes.DATE,
          allowNull: true,
          defaultValue: null,
          comment:   'Time at which the job becomes eligible for dispatch.',
        },

        started_at: {
          type:         DataTypes.DATE,
          allowNull:    true,
          defaultValue: null,
        },

        completed_at: {
          type:         DataTypes.DATE,
          allowNull:    true,
          defaultValue: null,
        },

        // â”€â”€ Retry Policy â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        retry_strategy: {
          type:         DataTypes.ENUM(...Object.values(RetryStrategy)),
          allowNull:    false,
          defaultValue: RetryStrategy.EXPONENTIAL,
          comment:      'Back-off algorithm applied between retry attempts.',
        },

        max_retries: {
          type:         DataTypes.TINYINT.UNSIGNED,
          allowNull:    false,
          defaultValue: 3,
        },

        retry_count: {
          type:         DataTypes.TINYINT.UNSIGNED,
          allowNull:    false,
          defaultValue: 0,
          comment:      'Incremented by Scheduler on each FAILED â†’ PENDING transition.',
        },

        retry_backoff_base_ms: {
          type:         DataTypes.INTEGER.UNSIGNED,
          allowNull:    false,
          defaultValue: 1000,
          comment:      'Base delay (ms) used in back-off formula.',
        },

        timeout_seconds: {
          type:         DataTypes.INTEGER.UNSIGNED,
          allowNull:    false,
          defaultValue: 300,
          comment:      'Max execution time. Scheduler forces FAILED after this.',
        },

        // â”€â”€ Deduplication â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        idempotency_key: {
          type:         DataTypes.STRING(500),
          allowNull:    true,
          defaultValue: null,
          comment:      'Client-supplied dedup key. Unique per (queue_id, key).',
        },

        // â”€â”€ Metadata â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        tags: {
          type:         DataTypes.JSON,
          allowNull:    true,
          defaultValue: null,
          comment:      'Arbitrary string array for filtering/alerting.',
        },
      },

      // â”€â”€ Model Options â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      {
        sequelize,
        modelName:     'Job',
        tableName:     'jobs',
        underscored:   true,
        freezeTableName: true,
        timestamps:    true,
        createdAt:     'created_at',
        updatedAt:     'updated_at',

        indexes: [
          // â”€â”€ Critical dispatch index â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          // Covers the worker atomic-claim query:
          //   WHERE queue_id = ? AND status = 'QUEUED' AND scheduled_at <= NOW()
          //   ORDER BY priority DESC, scheduled_at ASC
          // LIMIT 1 FOR UPDATE SKIP LOCKED
          {
            name:   'idx_jobs_dispatch',
            fields: ['queue_id', 'status', 'scheduled_at', 'priority'],
          },

          // â”€â”€ Scheduler timeout sweep â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          // WHERE status = 'RUNNING' AND started_at < (NOW() - timeout_seconds)
          {
            name:   'idx_jobs_timeout_scan',
            fields: ['status', 'started_at'],
          },

          // â”€â”€ Retry requeue scan â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          // WHERE status = 'FAILED' AND retry_count < max_retries
          {
            name:   'idx_jobs_retry_scan',
            fields: ['status', 'retry_count', 'scheduled_at'],
          },

          // â”€â”€ Cron materialization â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          // WHERE cron_expression IS NOT NULL AND status = 'PENDING'
          {
            name:   'idx_jobs_cron',
            fields: ['status', 'cron_expression'],
          },

          // â”€â”€ API list endpoints â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          // WHERE queue_id = ? AND status = ? ORDER BY created_at DESC
          {
            name:   'idx_jobs_queue_status_created',
            fields: ['queue_id', 'status', 'created_at'],
          },

          // â”€â”€ Idempotency constraint â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          {
            name:    'uq_jobs_idempotency_key',
            unique:  true,
            fields:  ['queue_id', 'idempotency_key'],
          },
        ],
      },
    );

    return Job;
  }
}

export default Job;

